apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mokv.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mokv.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "mokv.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "mokv.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "mokv.fullname" . }}
      labels: {{ include "mokv.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: {{ include "mokv.fullname" . }}-config-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |-
            ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
            cat > /var/run/mokv/config.yaml <<EOD
            data-dir: /var/run/mokv/data
            rpc-port: {{ .Values.rpcPort }}
            bind-addr: "$HOSTNAME.mokv.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.serfPort }}"
            $([ $ID != 0 ] && echo 'start-join-addrs: "mokv-0.mokv.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.serfPort }}"')
            bootstrap: $([ $ID = 0 ] && echo true || echo false )
            EOD
        volumeMounts:
        - name: datadir
          mountPath: /var/run/mokv/
      containers:
      - name: {{ include "mokv.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.rpcPort }}
          name: rpc
        - containerPort: {{ .Values.serfPort }}
          name: serf
        args:
          - --config-file=/var/run/mokv/config.yaml
        readinessProbe:
          grpc:
            port: {{ .Values.rpcPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: {{ .Values.rpcPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: datadir
          mountPath: /var/run/mokv/
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage }}